package com.localllm.chat.onboarding

/** European language options (ISO 639-1 code → native display name). */
object EuropeanLanguages {
    val all: Map<String, String> = linkedMapOf(
        "sq" to "Shqip",
        "eu" to "Euskara",
        "be" to "Беларуская",
        "bs" to "Bosanski",
        "bg" to "Български",
        "ca" to "Català",
        "hr" to "Hrvatski",
        "cs" to "Čeština",
        "da" to "Dansk",
        "nl" to "Nederlands",
        "en" to "English",
        "et" to "Eesti",
        "fi" to "Suomi",
        "fr" to "Français",
        "gl" to "Galego",
        "de" to "Deutsch",
        "el" to "Ελληνικά",
        "hu" to "Magyar",
        "is" to "Íslenska",
        "ga" to "Gaeilge",
        "it" to "Italiano",
        "lv" to "Latviešu",
        "lt" to "Lietuvių",
        "lb" to "Lëtzebuergesch",
        "mk" to "Македонски",
        "mt" to "Malti",
        "no" to "Norsk",
        "pl" to "Polski",
        "pt" to "Português",
        "ro" to "Română",
        "ru" to "Русский",
        "sr" to "Srpski",
        "sk" to "Slovenčina",
        "sl" to "Slovenščina",
        "es" to "Español",
        "sv" to "Svenska",
        "uk" to "Українська",
        "cy" to "Cymraeg",
    )
}
